### ISSUE TITLE
Error with fabric API version

### ISSUE THREAD

**Issue by drumadrian** [awslabs/sync-buckets-state-machine#17]
When runing **fab**

I get this exception: 
 

Traceback (most recent call last):

```
fabfile.py", line 24, in <module>
    from fabric.api import task
ImportError: No module named api

```
Here is the output of  **pip freeze**
```

asn1crypto==0.24.0
bcrypt==3.1.4
boto3==1.9.49
botocore==1.12.49
cffi==1.11.5
cryptography==2.4.2
docutils==0.14
enum34==1.1.6
fabric==2.4.0
futures==3.2.0
idna==2.7
invoke==1.2.0
ipaddress==1.0.22
jmespath==0.9.3
paramiko==2.4.2
pyasn1==0.4.4
pycparser==2.19
PyNaCl==1.3.0
python-dateutil==2.7.5
PyYAML==3.13
s3transfer==0.1.13
six==1.11.0
urllib3==1.24.1

```

This is the contents of **requirements.txt** in my virtualenv
```
Fabric>=1.12.0
boto3>=1.4.3
PyYAML>=3.12
```

**Comment by glez-aws** [comment]
Hi,

sorry to see that you’re having issues here. Unfortunately, Fabric versions newer than 1.x broke backward compatibility and therefore don't work with this code.

You can change the line:

Fabric>=1.12.0

to:

Fabric==1.120

in requirements.txt in order to force using the earlier, working version.

Hope this helps,
   Constantin

**Comment by drumadrian** [comment]
Thank you for your swift answer @glez-aws   🤓 

I will submit a pull request now for consideration.

**Comment by drumadrian** [comment]
Hi @glez-aws, 

I tried changing the Fabric version in the requirements.txt file and I got this error: 

`pip install -r requirements.txt 
Collecting Fabric==1.120 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement Fabric==1.120 (from -r requirements.txt (line 1)) (from versions: 0.0.1.macosx-10.4-i386, 0.0.2.macosx-10.4-i386, 0.0.3.macosx-10.4-i386, 0.0.4.macosx-10.4-i386, 0.0.5.macosx-10.4-i386, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0, 0.1.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.6.1, 1.6.2, 1.6.4, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.9.0, 1.9.1, 1.9.2, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.13.2, 1.14.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.4.0)
No matching distribution found for Fabric==1.120 (from -r requirements.txt (line 1))
`

I tried using combinations of the valid Fabric versions suggested in the error and that did not work.  Mostly because pip rejects most other versions being installed with an error like this: 

`Double requirement given: Fabric==0.1.0 (from -r requirements.txt (line 9)) (already in Fabric==0.0.9 (from -r requirements.txt (line 8)), name='Fabric')
`
and
`Double requirement given: Fabric==2.1.0 (from -r requirements.txt (line 9)) (already in Fabric==0.0.9 (from -r requirements.txt (line 8)), name='Fabric')
`

**Comment by drumadrian** [comment]
Is it possible to just use the YAML state machine description and build this myself in **Cloudformation** using the Lambda function code you have provided?

**Comment by glez-aws** [comment]
Hi Adrian,

sorry to see you're still having trouble to get this to work.

It looks like the requirements.txt file has two lines for fabric (the error message mentions lines 8 and 9).

Can you make sure there is only one line in requirements.txt and that this line looks like:

      Fabric>=1.12.0,<2.0

(This is a slightly more sophisticated line that basically makes sure you get the latest. 1.x.x version equal or later tha 1.12.0 but not from the new 2.0 branch.)

To you other question: Definitely yes. I’m only using Fabric as a "make" like utility here for building the solution. If I were to build this again, I would choose a different approach involving Serverless Application Model ([SAM][1]) and CodeBuild. So feel free to take the state machine YAML and the Lambda code and create your own build/deploy system. If you do, make sure to check out the YAML because it contains placeholders for the Lambda functions that are filles in by the script in fabfile.py.

If you do build your on build/deploy pipeline, you may find AWS CodeStar to be helpful in creating a basic scaffolding for your to build upon. I would suggest starting with the basic serverless web service template, then delete the API Gateway bits from the SAM template and instead insert the state machine definition, etc. It’ll be more work than fixing the Fabric line above, but it pays off for building other serverless apps in the future, so it's worth exploring and learning.

Hope this helps,
   Constantin

[1]: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html

**Comment by drumadrian** [comment]
Thanks @glez-aws  

I will try the new line in the requirements.txt 

If that doesn’t work I’ll see what else I can do. 

It seems like there is a magic version number that has the package needed between those 2 versions.

**Comment by drumadrian** [comment]
I won't be able to apply and test this update to my requirements file.
